test landing page... STILL fixing navbar links ???
Lambda-School-Labs/PT17_cityspire-a-fe pull request #7
Opened 2021-04-19 19:57 UTC by emfresh2o

Can't seem to link navbar 'login' to redirect to the main login form...  I also didn't not re-download a new repo, been working on the same repo since my 1st PR fixing the MapboxGL... so not sure if I needed to re-download a new repo of the main after everyone has upload their PR and was merged to main.

2021-04-19 20:15 UTC, mikepadiernos commented
You might have to update your branch because I have made a ton of tiny layout changes especially with the UserDashboardContainer.js.

2021-04-19 22:23 UTC, Rinzaru approved these changes, later dismissed

2021-04-20 02:17 UTC, mikepadiernos requested changes
> You might have to update your branch because I have made a ton of tiny layout changes that includes App.js, footer.js and especially with the UserDashboardContainer.js

2021-04-21 03:03 UTC, bobbyhalljr approved these changes

2021-04-21 03:04 UTC, mikepadiernos approved these changes

2021-04-21 03:04 UTC, merged